DROP DATABASE IF EXISTS plan_n_share_db;
CREATE DATABASE plan_n_share_db;

USE plan_n_share_db;

CREATE TABLE teams(
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(45) NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE users(
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    first_name VARCHAR(45) NOT NULL,
    last_name VARCHAR(45) NOT NULL,
    email VARCHAR(45) NOT NULL,
    password VARCHAR(45) NOT NULL,
    team_id INT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (team_id)
    REFERENCES teams(id)
    ON DELETE SET NULL
);

CREATE TABLE tasks(
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    category VARCHAR(45) DEFAULT 'Private',
    description VARCHAR(255) NOT NULL,
    status VARCHAR(45) DEFAULT 'To do',
    due_date DATE DEFAULT (CURRENT_DATE),
    assignee_id INT DEFAULT (user_id),
    user_id INT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (assignee_id)
    REFERENCES users(id)
    ON DELETE SET DEFAULT,
    FOREIGN KEY (user_id)
    REFERENCES users(id)
);